### ISSUE TITLE
Generated XAML code ignores SVG groups (SVG is flattened)

### ISSUE THREAD

**Issue by yankun** [wieslawsoltes/SvgToXaml#6]
Hi,

I've a SVG with multiple nested groups. All groups are having various IDs. I would like to use these grouping system to conditionally hide and show parts of my image.

However exporting the SVG to XAML flattens it. Looking into the code however, it seems like this support was at least planned?

I've poked around and saw, that Skia only provides Commands which are translated to XAML, with the groups already beeing lost.

Do you think there is a possibility to keep the exact same grouping from the SVG and transfer it into drawing groups?

**Comment by wieslawsoltes** [comment]
I don't think that's easy to do with current way Svg is rendered.

**Comment by yankun** [comment]
What about splitting the XML in the SVG manually and "fake" multiple smaller SVGs and then put them together? I gonna try this within the next days :)

**Comment by wieslawsoltes** [comment]
> What about splitting the XML in the SVG manually and "fake" multiple smaller SVGs and then put them together? I gonna try this within the next days :)

If you split svg then you can generate xaml library with separate drawing resources
