### ISSUE TITLE
Add support to use a custom color

### ISSUE THREAD

**Issue by Symbai** [wieslawsoltes/SvgToXaml#9]
Sometimes SVGs are multi colored or have a specific color but we need/want this SVG to be a specific custom color. For example make this image all white or black or yellow. At the moment we have to replace all colors ourselves after its converted. It would be useful to define a custom string (color, but string is better so we could also use our own bindings) and the converter just uses that.

So instead of:

```XAML
<Image>
  <Image.Resources>
    <SolidColorBrush x:Key="Brush0" Color="#FFAE938D" />
    <SolidColorBrush x:Key="Brush1" Color="#FFAAB1BA" />
    <SolidColorBrush x:Key="Brush2" Color="#FF51565F" />
  </Image.Resources>
</Image>
```

We define custom color to be `#000000`

It generates:
```XAML
<Image>
  <Image.Resources>
    <SolidColorBrush x:Key="Brush0" Color="#000000" />
    <SolidColorBrush x:Key="Brush1" Color="#000000" />
    <SolidColorBrush x:Key="Brush2" Color="#000000" />
  </Image.Resources>
</Image>
```

Or we define custom color to be `{DynamicResource MyCustomColor}`

It generates:
```XAML
<Image>
  <Image.Resources>
    <SolidColorBrush x:Key="Brush0" Color="{DynamicResource MyCustomColor}" />
    <SolidColorBrush x:Key="Brush1" Color="{DynamicResource MyCustomColor}" />
    <SolidColorBrush x:Key="Brush2" Color="{DynamicResource MyCustomColor}" />
  </Image.Resources>
</Image>
```

**Comment by wieslawsoltes** [comment]
Use reuse resources option to generate such option.
